# Generated by Django 3.1.1 on 2020-09-18 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hod', models.BooleanField(default=False)),
                ('is_pur', models.BooleanField(default=False)),
                ('is_fin', models.BooleanField(default=False)),
                ('is_gm', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Retired'), related_name='profiles', to='orders.department')),
                ('user', models.OneToOneField(on_delete=models.SET('Retired'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
