# Generated by Django 3.1.1 on 2020-09-09 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hod', models.BooleanField(default=False)),
                ('is_pur', models.BooleanField(default=False)),
                ('is_fin', models.BooleanField(default=False)),
                ('is_gm', models.BooleanField(default=False)),
                ('department', models.CharField(choices=[('EN', 'Engineering'), ('FI', 'Finance'), ('FB', 'Food and Beverage'), ('RD', 'Rooms Division'), ('SM', 'Sales and Marketing')], default='Not assigned', max_length=100)),
                ('user', models.OneToOneField(on_delete=models.SET('Retired'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
