# Generated by Django 3.1.1 on 2020-10-27 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('HOD', 'HOD'), ('PUR', 'PUR'), ('FIN', 'FIN'), ('GM', 'GM')], max_length=5)),
                ('approved', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('win_username', models.CharField(default=None, max_length=200)),
                ('win_pcname', models.CharField(default=None, max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='orders.order')),
                ('user', models.ForeignKey(on_delete=models.SET(None), related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hod', models.BooleanField(default=False)),
                ('is_pur', models.BooleanField(default=False)),
                ('is_fin', models.BooleanField(default=False)),
                ('is_gm', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Retired'), related_name='profiles', to='orders.department')),
                ('user', models.OneToOneField(on_delete=models.SET('Retired'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
