# Generated by Django 3.1.1 on 2020-10-27 14:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sign_as',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('HOD', 'HOD'), ('PUR', 'PUR'), ('FIN', 'FIN'), ('GM', 'GM')], default=None, max_length=14, null=True),
        ),
    ]
