# Generated by Django 3.1.1 on 2020-10-28 13:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_sign_as'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_fin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_gm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_hod',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_pur',
        ),
        migrations.AlterField(
            model_name='profile',
            name='sign_as',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Head of Department'), (1, 'Purchasing Manager'), (2, 'Financial Controller'), (3, 'General Manager')], default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='level',
            field=models.CharField(choices=[(0, 'Head of Department'), (1, 'Purchasing Manager'), (2, 'Financial Controller'), (3, 'General Manager')], max_length=5),
        ),
    ]
