# Generated by Django 3.1.1 on 2020-09-21 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='NA', max_length=5)),
                ('name', models.CharField(default='Not assigned', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Заказ')),
                ('supplier', models.CharField(blank=True, max_length=250, null=True, verbose_name='Поставщик')),
                ('amount', models.DecimalField(decimal_places=2, help_text='включая 20% НДС', max_digits=12, verbose_name='К оплате')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('all_signed', models.BooleanField(null=True)),
                ('department', models.ForeignKey(on_delete=models.SET(None), related_name='orders', to='orders.department')),
                ('requested_by', models.ForeignKey(on_delete=models.SET(None), related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
