# Generated by Django 3.1.1 on 2020-09-09 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('hod_approved', models.BooleanField(null=True)),
                ('pur_approved', models.BooleanField(null=True)),
                ('fin_approved', models.BooleanField(null=True)),
                ('gm_approved', models.BooleanField(null=True)),
                ('all_approved', models.BooleanField(null=True)),
                ('fin_user', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Retired'), related_name='fin_approved', to=settings.AUTH_USER_MODEL)),
                ('gm_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET('Retired'), related_name='gm_approved', to=settings.AUTH_USER_MODEL)),
                ('hod_user', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Retired'), related_name='hod_approved', to=settings.AUTH_USER_MODEL)),
                ('pur_user', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Retired'), related_name='pur_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=models.SET('Retired'), related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
