# Generated by Django 3.1.1 on 2020-10-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200921_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='all_signed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
